name: "Oscar CI Package Installation"

inputs:
  config:
    description: "Oscar CI config file"
    required: true
    default: "ci/config/standalone.yaml"

runs:
  using: "composite"
  steps:
  - name: Install Oscar
    run: |
      set -e
      ci/install.rb
    env:
      OSCAR_CI_CONFIG: ${{ inputs.config }}
    shell: bash
